import {configureStore} from '@reduxjs/toolkit';
import todoReducer from '../features/todo/todoSlice';        // todoReducer represents ONE single reducer function generated by createSlice, which internally handles ALL reducers like addTodo, removeTodo, updateTodo.
                                                             // We import it here to combine it into the Redux store. 
const store = configureStore({
    reducer: todoReducer                     // todoSlice.reducer IS the same thing as todoReducer. This represents all list of reducers
})

export default store;